blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/vuejs/rfcs/discussions
    about: Suggest new features for consideration
  - name: Discord Chat
    url: https://chat.vuejs.org
    about: Ask questions and discuss with other Vue users in real time.
  - name: Questions & Discussions
    url: https://github.com/vuejs/core/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
  - name: Patreon
    url: https://www.patreon.com/evanyou
    about: Love Vue.js? Please consider supporting us via Patreon.
  - name: Open Collective
    url: https://opencollective.com/vuejs/donate
    about: Love Vue.js? Please consider supporting us via Open Collective.
